### ISSUE TITLE
No File/Folder Rows displayed in main window when broken link is encountered

### ISSUE THREAD

**Issue by MidnightDriveApps** [BSFEMA/linux_file_rename_utility#1]
This is a pretty rockin' renaming utility, got several features I've been looking for for years in a bulk renamer tool! 

An issue that I've run into that is a bit of a show stopper is that when it encounters a broken link, even far deep within subfolders of the selected folder, (which apparently are quite frequent in the /home subfolders buried within program config folders) nothing (no files or folder rows) is shown in the main window. The program GUI responds normally (fields can be entered, different fodlers can be selected,etc.) and doesn't display any warning/indicator of what's wrong - thankfully a Stack Trace is outputted to the console when run from terminal:

```
Traceback (most recent call last):
  File "linux_file_rename_utility.py", line 275, in entry_Folder_Path_changed
    populate_files_Full(self.builder.get_object("entry_Mask").get_text(),
  File "linux_file_rename_utility.py", line 2279, in populate_files_Full
    part6 = human_readable_filesize(os.stat(part0).st_size)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cc/.mozilla/firefox/ggll95mh.default-release/lock'
```

I've been looking to get into both Python coding as well as contributing to open source projects so I may try my hand at implementing a fix and submitting a pull request for this; as I've not done so before as far as a public github project is concerned any guidance would be welcome, whether regarding technical points and/or community etiquette

Thanks to the developer for this kickass tool!

**Comment by BSFEMA** [comment]
Thanks!  I'm glad someone is actually using it besides me!

This should be fixed in v1.9.

It no longer crashes when it encounters a broken symlink or a file/folder that no long exists when loading the data grid.  Broken symlinks or file/folder that no longer exist will have their File Size and Date Modified set to "BROKEN LINK!!!".  If the file/folder is a broken symlink, then it will not be renamed, it will get the "Current Name's Full Path doesn't exist" status.
